services:
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      FLASK_APP: cardmanager.py
      FLASK_RUN_HOST: 0.0.0.0
      TONITUNES_HOME: /root/.tonitunes
      TONITUNES_CONFIG_NAME: development
    volumes:
      - ${HOME}/.tonitunes:/root/.tonitunes
