version: '3.8'

services:
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      FLASK_APP: cardmanager.py
      FLASK_RUN_HOST: 0.0.0.0
      FLASK_CONFIG: production
      TONITUNES_HOME: root/.tonitunes
    volumes:
      - ${HOME}/.tonitunes:/root/.tonitunes
